# Generated by Django 4.2 on 2023-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_person_post_person_that_make_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='person_that_make_it',
        ),
        migrations.AddField(
            model_name='post',
            name='person_that_make_it',
            field=models.ManyToManyField(null=True, to='Posts.person'),
        ),
    ]
