# Generated by Django 4.2 on 2023-05-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_remove_post_person_that_make_it_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='person_that_make_it',
        ),
        migrations.AddField(
            model_name='post',
            name='person_that_make_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.person'),
        ),
    ]
